-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrhqfOWAHyWKAkvM4
uvMpbpuBD6bt+oMADLu34AVff7mgCgYIKoZIzj0DAQehRANCAATDV7EoZQEW6htC
253yX021enuLBBLFfCmRx8gs74hjgaclA8yMTGpgYBnOwAY5MAffW0WjKBysq1OJ
xAeomUvj
-----END PRIVATE KEY-----